const crypto = require("crypto");
const fs = require("fs");
const os = require("os");
const path = require("path");
const ftp = require("basic-ftp");

const TOOL_ROOT = __dirname;
const BASELINE_PATH = path.join(TOOL_ROOT, "security-baseline.json");
const HISTORY_PATH = path.join(TOOL_ROOT, "security-scan-history.json");
const EVIDENCE_ROOT = path.join(TOOL_ROOT, "security-evidence");

const APACHE_UPLOAD_GUARD = `# Generated by the local FTP security tool.
<FilesMatch "\\.(php[0-9]?|phtml|pht|phar|cgi|pl|py|sh)$">
  <IfModule mod_authz_core.c>
    Require all denied
  </IfModule>
  <IfModule !mod_authz_core.c>
    Order allow,deny
    Deny from all
  </IfModule>
</FilesMatch>
<IfModule mod_mime.c>
  RemoveHandler .php .php3 .php4 .php5 .php7 .php8 .phtml .pht .phar .cgi .pl .py .sh
  RemoveType .php .php3 .php4 .php5 .php7 .php8 .phtml .pht .phar .cgi .pl .py .sh
</IfModule>
`;

const IIS_UPLOAD_GUARD = `<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <system.webServer>
    <security>
      <requestFiltering>
        <fileExtensions allowUnlisted="true">
          <add fileExtension=".php" allowed="false" />
          <add fileExtension=".phtml" allowed="false" />
          <add fileExtension=".pht" allowed="false" />
          <add fileExtension=".phar" allowed="false" />
          <add fileExtension=".cgi" allowed="false" />
          <add fileExtension=".pl" allowed="false" />
        </fileExtensions>
      </requestFiltering>
    </security>
  </system.webServer>
</configuration>
`;

const EXECUTABLE_EXTENSIONS = new Set([
  ".php", ".php3", ".php4", ".php5", ".php7", ".php8", ".phtml", ".pht", ".phar", ".inc",
  ".asp", ".aspx", ".ashx", ".jsp", ".jspx", ".cgi", ".pl", ".py", ".sh",
]);

const TEXT_EXTENSIONS = new Set([
  ...EXECUTABLE_EXTENSIONS,
  ".htm", ".html", ".shtml", ".js", ".mjs", ".cjs", ".css", ".json", ".xml", ".txt",
  ".ini", ".conf", ".config", ".yml", ".yaml", ".md",
]);

const UPLOAD_LIKE_SEGMENTS = new Set([
  "upload", "uploads", "uploaded", "files", "images", "image", "img", "media", "assets", "static",
  "tmp", "temp",
]);

const SKIP_DIRECTORIES = new Set([".", "..", ".git", ".svn", "node_modules"]);

const CONTENT_RULES = [
  {
    id: "eval-base64",
    label: "动态执行与 Base64 解码组合",
    severity: "high",
    test: (text) => /\b(?:eval|assert)\s*\([^)]*\bbase64_decode\s*\(/is.test(text) || /\bbase64_decode\s*\([^)]*\)[\s\S]{0,160}\b(?:eval|assert)\s*\(/is.test(text),
  },
  {
    id: "compressed-payload",
    label: "压缩解码后动态执行",
    severity: "high",
    test: (text) => /\b(?:gzinflate|gzuncompress|str_rot13)\s*\([\s\S]{0,220}\b(?:eval|assert)\s*\(/is.test(text) || /\b(?:eval|assert)\s*\([\s\S]{0,220}\b(?:gzinflate|gzuncompress|str_rot13)\s*\(/is.test(text),
  },
  {
    id: "request-code-execution",
    label: "直接执行外部请求参数",
    severity: "high",
    test: (text) => /\b(?:eval|assert|system|exec|shell_exec|passthru|popen|proc_open)\s*\(\s*\$_(?:GET|POST|REQUEST|COOKIE)/is.test(text),
  },
  {
    id: "dangerous-handler",
    label: "把静态扩展映射为脚本执行",
    severity: "high",
    test: (text, remotePath) => /(?:AddHandler|AddType|SetHandler)[^\r\n]*(?:php|cgi|application\/x-httpd)/i.test(text) && /(?:jpe?g|png|gif|ico|txt|html?)/i.test(text) && /(?:\.htaccess|\.user\.ini|web\.config)$/i.test(remotePath),
  },
  {
    id: "php-in-static-file",
    label: "静态文件中出现 PHP 代码标记",
    severity: "high",
    test: (text, remotePath) => /<\?(?:php|=)/i.test(text) && !EXECUTABLE_EXTENSIONS.has(path.posix.extname(remotePath.toLowerCase())),
  },
  {
    id: "long-encoded-payload",
    label: "疑似长编码载荷",
    severity: "medium",
    test: (text) => /[A-Za-z0-9+/]{1600,}={0,2}/.test(text) && /\b(?:base64_decode|eval|assert|gzinflate|gzuncompress)\b/i.test(text),
  },
  {
    id: "obfuscated-variable-call",
    label: "高密度变量函数调用",
    severity: "medium",
    test: (text) => /\$[A-Za-z_][A-Za-z0-9_]*\s*=\s*['"][A-Za-z_]{3,}['"];[\s\S]{0,240}\$[A-Za-z_][A-Za-z0-9_]*\s*\(/is.test(text) && /\$_(?:GET|POST|REQUEST|COOKIE)/i.test(text),
  },
];

function normalizeRemotePath(value) {
  return String(value || "")
    .replace(/\\/g, "/")
    .replace(/^\/+/, "")
    .replace(/\/{2,}/g, "/")
    .replace(/\/$/, "");
}

function normalizeRemoteRoot(value) {
  const root = normalizeRemotePath(value);
  return root && root !== "." ? root : "";
}

function safeLocalPath(root, relativePath) {
  const target = path.resolve(root, normalizeRemotePath(relativePath));
  const resolvedRoot = path.resolve(root);
  if (target !== resolvedRoot && !target.startsWith(`${resolvedRoot}${path.sep}`)) {
    throw new Error(`Unsafe local path: ${relativePath}`);
  }
  return target;
}

function sha256Buffer(buffer) {
  return crypto.createHash("sha256").update(buffer).digest("hex");
}

function sha256File(filePath) {
  return sha256Buffer(fs.readFileSync(filePath));
}

function siteFingerprint(config) {
  return crypto
    .createHash("sha256")
    .update([config.host || "", config.port || 21, config.user || "", normalizeRemoteRoot(config.remoteRoot)].join("|"))
    .digest("hex")
    .slice(0, 20);
}

function isExecutablePath(remotePath) {
  return EXECUTABLE_EXTENSIONS.has(path.posix.extname(normalizeRemotePath(remotePath).toLowerCase()));
}

function isSensitiveControlFile(remotePath) {
  const name = path.posix.basename(normalizeRemotePath(remotePath)).toLowerCase();
  return name === ".htaccess" || name === ".user.ini" || name === "web.config" || name === "php.ini";
}

function isUploadLikePath(remotePath) {
  const parts = normalizeRemotePath(remotePath).toLowerCase().split("/");
  return parts.some((part) => UPLOAD_LIKE_SEGMENTS.has(part));
}

function hasDoubleExecutableExtension(remotePath) {
  const name = path.posix.basename(normalizeRemotePath(remotePath)).toLowerCase();
  return /\.(?:jpe?g|png|gif|webp|ico|svg|txt|pdf|zip|rar)\.(?:php\d?|phtml|pht|phar|asp|aspx|jsp|cgi|pl)$/i.test(name);
}

function shouldInspectContent(file, maxBytes) {
  if (Number(file.size || 0) > maxBytes) return false;
  const remotePath = normalizeRemotePath(file.path).toLowerCase();
  const name = path.posix.basename(remotePath);
  const extension = path.posix.extname(remotePath);
  if (TEXT_EXTENSIONS.has(extension) || isSensitiveControlFile(remotePath)) return true;
  if (!isUploadLikePath(remotePath)) return false;
  return [".jpg", ".jpeg", ".png", ".gif", ".webp", ".ico", ".svg", ".dat", ".tmp"].includes(extension) || !extension || name.startsWith(".");
}

function contentRulesFor(buffer, remotePath) {
  const text = buffer.toString("utf8");
  return CONTENT_RULES.filter((rule) => rule.test(text, remotePath)).map((rule) => ({
    id: rule.id,
    label: rule.label,
    severity: rule.severity,
  }));
}

function severityWeight(value) {
  if (value === "high") return 3;
  if (value === "medium") return 2;
  return 1;
}

function maxSeverity(values) {
  return values.reduce((current, value) => severityWeight(value) > severityWeight(current) ? value : current, "low");
}

function remoteModifiedAt(item) {
  if (item.modifiedAt instanceof Date && !Number.isNaN(item.modifiedAt.getTime())) {
    return item.modifiedAt.toISOString();
  }
  return String(item.rawModifiedAt || item.modifiedAt || "");
}

function sleep(milliseconds) {
  return new Promise((resolve) => setTimeout(resolve, milliseconds));
}

function isRetryableFtpError(error) {
  const message = String(error?.message || error || "").toLowerCase();
  return (
    message.includes("timeout")
    || message.includes("server sent fin")
    || message.includes("client is closed")
    || message.includes("connection closed")
    || message.includes("econnreset")
    || message.includes("etimedout")
    || message.includes("421")
    || message.includes("425")
    || message.includes("426")
  );
}

async function connectFtp(config, clientFactory) {
  const client = clientFactory
    ? clientFactory()
    : new ftp.Client(Number(config.securityTimeoutMs || config.timeoutMs || 60000));
  if (client.ftp) client.ftp.verbose = Boolean(config.verbose);
  await client.access({
    host: config.host,
    port: Number(config.port || 21),
    user: config.user,
    password: config.password,
    secure: Boolean(config.secure),
  });
  const loginDir = await client.pwd().catch(() => "");
  const remoteRoot = normalizeRemoteRoot(config.remoteRoot);
  if (remoteRoot) await client.cd(remoteRoot);
  const rootDir = await client.pwd().catch(() => loginDir);
  return { client, loginDir, rootDir };
}

async function listRemoteTree(client, options = {}) {
  const files = [];
  const maxFiles = Math.max(100, Number(options.maxFiles || 30000));
  const maxDepth = Math.max(2, Number(options.maxDepth || 40));
  let directoryCount = 0;
  let truncated = false;

  async function walk(relativeDir, depth) {
    if (options.shouldCancel?.()) {
      const error = new Error("扫描已由用户取消。");
      error.code = "SCAN_CANCELLED";
      throw error;
    }
    if (truncated || depth > maxDepth) return;
    const items = options.listDirectory
      ? await options.listDirectory(relativeDir || ".")
      : await client.list(relativeDir || ".");
    directoryCount += 1;
    for (const item of items) {
      if (options.shouldCancel?.()) {
        const error = new Error("扫描已由用户取消。");
        error.code = "SCAN_CANCELLED";
        throw error;
      }
      const name = String(item.name || "");
      if (!name || SKIP_DIRECTORIES.has(name.toLowerCase())) continue;
      const remotePath = normalizeRemotePath(relativeDir ? `${relativeDir}/${name}` : name);
      if (!remotePath || remotePath.split("/").includes("..")) continue;
      const isDirectory = item.type === 2 || item.type === "directory";
      const isFile = item.type === 1 || item.type === "file" || (!isDirectory && Number(item.size) >= 0);
      if (isDirectory) {
        await walk(remotePath, depth + 1);
        if (truncated) return;
      } else if (isFile) {
        files.push({
          path: remotePath,
          size: Number(item.size || 0),
          modifiedAt: remoteModifiedAt(item),
        });
        options.onProgress?.({ stage: "listing", files: files.length, directories: directoryCount, path: remotePath });
        if (files.length >= maxFiles) {
          truncated = true;
          return;
        }
      }
    }
  }

  await walk("", 0);
  return { files, directoryCount, truncated };
}

async function downloadRemoteBuffer(client, remotePath, tempRoot) {
  fs.mkdirSync(tempRoot, { recursive: true });
  const tempPath = path.join(tempRoot, `${crypto.randomUUID()}.scan`);
  try {
    await client.downloadTo(tempPath, normalizeRemotePath(remotePath));
    return fs.readFileSync(tempPath);
  } finally {
    fs.rmSync(tempPath, { force: true });
  }
}

function loadJson(filePath, fallback) {
  try {
    return JSON.parse(fs.readFileSync(filePath, "utf8"));
  } catch (_error) {
    return fallback;
  }
}

function readBaseline(filePath = BASELINE_PATH) {
  return loadJson(filePath, null);
}

function writeBaseline(baseline, filePath = BASELINE_PATH) {
  fs.writeFileSync(filePath, `${JSON.stringify(baseline, null, 2)}\n`, "utf8");
}

function baselineInfo(baseline) {
  if (!baseline) return { exists: false, createdAt: "", files: 0, hashedFiles: 0, fingerprint: "" };
  const files = Object.values(baseline.files || {});
  return {
    exists: true,
    createdAt: baseline.createdAt || "",
    files: files.length,
    hashedFiles: files.filter((item) => item.sha256).length,
    fingerprint: baseline.fingerprint || "",
    version: Number(baseline.version || 1),
  };
}

function buildBaseline(scanResult) {
  if (!scanResult || !scanResult.snapshot) throw new Error("Scan snapshot is missing.");
  return {
    version: 2,
    createdAt: new Date().toISOString(),
    fingerprint: scanResult.fingerprint,
    remoteRoot: scanResult.remoteRoot || "",
    files: scanResult.snapshot,
  };
}

function publicScanResult(result) {
  if (!result) return null;
  const { snapshot: _snapshot, ...safe } = result;
  return safe;
}

function appendHistory(result, filePath = HISTORY_PATH) {
  const history = loadJson(filePath, []);
  history.unshift({
    scannerVersion: Number(result.scannerVersion || 2),
    scanType: result.scanType || "full",
    scanId: result.scanId,
    startedAt: result.startedAt,
    finishedAt: result.finishedAt,
    fingerprint: result.fingerprint,
    summary: result.summary,
    warnings: result.warnings,
    topFindings: result.findings.slice(0, 20),
  });
  fs.writeFileSync(filePath, `${JSON.stringify(history.slice(0, 30), null, 2)}\n`, "utf8");
  return history.slice(0, 30);
}

function readHistory(filePath = HISTORY_PATH) {
  return loadJson(filePath, []);
}

function createLocalHardeningFiles(config) {
  const localRoot = path.resolve(TOOL_ROOT, config.localRoot || "..");
  const configuredDirs = Array.isArray(config.imageDirs) && config.imageDirs.length
    ? config.imageDirs
    : ["static", "uploads"];
  const directories = [...new Set(configuredDirs.map(normalizeRemotePath).filter(Boolean))];
  const created = [];
  const skipped = [];

  for (const directory of directories) {
    const directoryPath = safeLocalPath(localRoot, directory);
    if (!fs.existsSync(directoryPath) || !fs.statSync(directoryPath).isDirectory()) {
      skipped.push({ path: directory, reason: "本地目录不存在" });
      continue;
    }

    for (const [name, content] of [[".htaccess", APACHE_UPLOAD_GUARD], ["web.config", IIS_UPLOAD_GUARD]]) {
      const relativePath = normalizeRemotePath(`${directory}/${name}`);
      const targetPath = safeLocalPath(localRoot, relativePath);
      if (fs.existsSync(targetPath)) {
        skipped.push({ path: relativePath, reason: "已有文件，未覆盖" });
        continue;
      }
      fs.writeFileSync(targetPath, content, { encoding: "utf8", flag: "wx" });
      created.push(relativePath);
    }
  }

  return {
    created,
    skipped,
    note: "规则仅对 Apache/IIS 生效；Nginx 需要在服务器配置中单独禁止上传目录执行脚本。",
  };
}

async function scanRemoteSite(config, options = {}) {
  if (!config.host || !config.user || !config.password) {
    throw new Error("请先完整配置 FTP 地址、用户名和密码。");
  }
  const startedAt = new Date().toISOString();
  const scanId = crypto.randomUUID();
  const fingerprint = siteFingerprint(config);
  const baseline = options.baseline === undefined ? readBaseline(options.baselinePath) : options.baseline;
  const baselineMatches = Boolean(baseline && baseline.fingerprint === fingerprint);
  const scanType = options.scanType === "full" || !baselineMatches ? "full" : "incremental";
  const warnings = [];
  if (!baseline) warnings.push("尚未建立可信基线，本次仍会检查可疑路径和代码特征，但不能判断哪些文件刚被新增或篡改。");
  else if (!baselineMatches) warnings.push("现有基线属于另一个 FTP 站点或远程目录，本次不会使用它做变化对比。");

  const maxFileBytes = Math.max(64 * 1024, Number(config.securityMaxFileSizeKb || 2048) * 1024);
  const maxFiles = Math.max(100, Number(config.securityMaxFiles || 30000));
  const localRoot = path.resolve(TOOL_ROOT, config.localRoot || "..");
  const tempRoot = fs.mkdtempSync(path.join(os.tmpdir(), "pboot-ftp-security-"));
  const findings = [];
  const findingKeys = new Set();
  const snapshot = {};
  let contentScanned = 0;
  let newFiles = 0;
  let modifiedFiles = 0;
  let missingFiles = 0;
  let remoteOnlyCode = 0;
  let skippedUnchanged = 0;
  let metadataChanged = 0;
  let timestampAnomalies = 0;
  let ftpOperations = 0;
  const maxRetries = Math.max(0, Number(config.securityMaxRetries ?? config.maxRetries ?? 4));
  const reconnectEvery = Math.max(0, Number(config.securityReconnectEvery ?? config.reconnectEvery ?? 60));
  const retryDelayMs = Math.max(0, Number(config.securityRetryDelayMs ?? 750));

  function addFinding(finding) {
    const key = `${finding.category}|${finding.path}|${finding.title}`;
    if (findingKeys.has(key)) return;
    findingKeys.add(key);
    findings.push({
      id: crypto.createHash("sha1").update(key).digest("hex").slice(0, 16),
      severity: "low",
      detail: "",
      ...finding,
    });
  }

  let connection;

  async function closeConnection() {
    try { connection?.client?.close(); } catch (_error) { /* ignore close errors */ }
    connection = null;
  }

  async function openConnection(reason = "initial") {
    await closeConnection();
    connection = await connectFtp(config, options.clientFactory);
    options.onConnection?.({ reason, operations: ftpOperations });
    return connection;
  }

  async function runFtpOperation(action, context = {}) {
    let reconnectReason = connection ? "scheduled" : "initial";
    for (let attempt = 0; attempt <= maxRetries; attempt += 1) {
      if (options.shouldCancel?.()) {
        const error = new Error("扫描已由用户取消。");
        error.code = "SCAN_CANCELLED";
        throw error;
      }
      try {
        const scheduledReconnect = Boolean(
          connection && reconnectEvery > 0 && ftpOperations > 0 && ftpOperations % reconnectEvery === 0,
        );
        if (!connection || scheduledReconnect) {
          await openConnection(scheduledReconnect ? "scheduled" : reconnectReason);
        }
        const result = await action(connection.client);
        ftpOperations += 1;
        return result;
      } catch (error) {
        const retryable = isRetryableFtpError(error);
        await closeConnection();
        if (!retryable || attempt >= maxRetries) {
          if (!retryable) throw error;
          const finalError = new Error(`${error.message || String(error)}（FTP 已自动重试 ${maxRetries} 次仍失败）`);
          finalError.code = error.code;
          finalError.cause = error;
          throw finalError;
        }
        const nextAttempt = attempt + 1;
        reconnectReason = "retry";
        options.onProgress?.({
          stage: "reconnecting",
          current: context.current,
          total: context.total,
          path: context.path || "",
        });
        options.onRetry?.({
          attempt: nextAttempt,
          maxRetries,
          stage: context.stage || "ftp",
          path: context.path || "",
          message: error.message || String(error),
        });
        await sleep(retryDelayMs * nextAttempt);
      }
    }
    throw new Error("FTP 操作重试异常结束。");
  }

  try {
    const tree = await listRemoteTree(null, {
      maxFiles,
      maxDepth: config.securityMaxDepth || 40,
      onProgress: options.onProgress,
      shouldCancel: options.shouldCancel,
      listDirectory: (relativeDir) => runFtpOperation(
        (client) => client.list(relativeDir),
        { stage: "listing", path: relativeDir },
      ),
    });
    if (tree.truncated) warnings.push(`远程文件超过 ${maxFiles} 个，本次扫描已达到上限，结果不完整。`);

    for (let index = 0; index < tree.files.length; index += 1) {
      if (options.shouldCancel?.()) {
        const error = new Error("扫描已由用户取消。");
        error.code = "SCAN_CANCELLED";
        throw error;
      }
      const file = tree.files[index];
      const remotePath = normalizeRemotePath(file.path);
      const executable = isExecutablePath(remotePath);
      const uploadLike = isUploadLikePath(remotePath);
      const sensitiveControl = isSensitiveControlFile(remotePath);
      const baseFile = baselineMatches ? baseline.files?.[remotePath] : null;
      const localPath = safeLocalPath(localRoot, remotePath);
      const localFile = fs.existsSync(localPath) && fs.statSync(localPath).isFile() ? fs.statSync(localPath) : null;
      const baselineMetadataChanged = Boolean(baseFile && (
        Number(baseFile.size || 0) !== Number(file.size || 0)
        || (baseFile.modifiedAt && file.modifiedAt && baseFile.modifiedAt !== file.modifiedAt)
      ));
      let remoteHash = "";
      let buffer = null;
      const inspectable = shouldInspectContent(file, maxFileBytes);

      if (hasDoubleExecutableExtension(remotePath)) {
        addFinding({
          severity: "high",
          category: "dangerous-path",
          path: remotePath,
          title: "发现双扩展可执行文件",
          detail: "图片、文本或压缩包扩展后又带脚本扩展，属于常见伪装方式。",
          size: file.size,
          modifiedAt: file.modifiedAt,
        });
      }
      if (executable && uploadLike) {
        addFinding({
          severity: "high",
          category: "executable-in-upload",
          path: remotePath,
          title: "上传或静态目录中出现可执行脚本",
          detail: "正常图片/附件目录不应包含可由服务器执行的脚本文件。",
          size: file.size,
          modifiedAt: file.modifiedAt,
        });
      }

      const localSizeChanged = Boolean(localFile && Number(localFile.size) !== Number(file.size || 0));
      const remoteOnly = !localFile;
      const missingTrustedHash = Boolean(baseFile && inspectable && !baseFile.sha256);
      const inspectContent = inspectable && (
        scanType === "full"
        || !baselineMatches
        || !baseFile
        || baselineMetadataChanged
        || missingTrustedHash
        || (executable && (uploadLike || remoteOnly || localSizeChanged))
        || (!executable && uploadLike && (remoteOnly || localSizeChanged))
      );

      if (baselineMatches && baseFile && !baselineMetadataChanged && !inspectContent) {
        skippedUnchanged += 1;
      }

      if (inspectContent) {
        try {
          buffer = await runFtpOperation(
            (client) => downloadRemoteBuffer(client, remotePath, tempRoot),
            { stage: "content", current: index + 1, total: tree.files.length, path: remotePath },
          );
          remoteHash = sha256Buffer(buffer);
          contentScanned += 1;
          const matchedRules = contentRulesFor(buffer, remotePath);
          if (matchedRules.length) {
            addFinding({
              severity: maxSeverity(matchedRules.map((item) => item.severity)),
              category: "content-signature",
              path: remotePath,
              title: "文件内容命中高风险代码特征",
              detail: matchedRules.map((item) => item.label).join("；"),
              rules: matchedRules.map((item) => item.id),
              size: file.size,
              modifiedAt: file.modifiedAt,
            });
          }
        } catch (error) {
          warnings.push(`无法读取 ${remotePath}：${error.message || String(error)}`);
        }
      }

      snapshot[remotePath] = {
        size: file.size,
        modifiedAt: file.modifiedAt,
        sha256: remoteHash || (!baselineMetadataChanged ? baseFile?.sha256 || "" : ""),
      };

      if (!baseFile && baselineMatches) {
        newFiles += 1;
        const baselineTime = Date.parse(baseline.createdAt || "");
        const remoteTime = Date.parse(file.modifiedAt || "");
        const backdated = Number.isFinite(baselineTime) && Number.isFinite(remoteTime) && remoteTime < baselineTime - 5 * 60 * 1000;
        if (backdated) {
          timestampAnomalies += 1;
          addFinding({
            severity: executable || sensitiveControl ? "high" : "medium",
            category: "timestamp-anomaly",
            path: remotePath,
            title: "基线后新增但文件时间早于基线",
            detail: "可能是上传时保留了旧时间，也可能有人刻意回写时间；新路径仍按异常新增文件核对。",
            size: file.size,
            modifiedAt: file.modifiedAt,
          });
        }
        addFinding({
          severity: executable || sensitiveControl ? "high" : "low",
          category: "new-file",
          path: remotePath,
          title: executable || sensitiveControl ? "基线后新增敏感文件" : "基线后新增文件",
          detail: executable || sensitiveControl ? "请确认该脚本或服务器控制文件是否由本次正规发布产生。" : "普通静态资源新增，仅作变化记录。",
          size: file.size,
          modifiedAt: file.modifiedAt,
        });
      } else if (baseFile) {
        const hashChanged = Boolean(baseFile.sha256 && remoteHash && baseFile.sha256 !== remoteHash);
        if (hashChanged || (!baseFile.sha256 && baselineMetadataChanged)) {
          modifiedFiles += 1;
          addFinding({
            severity: executable || sensitiveControl ? "high" : "medium",
            category: "modified-file",
            path: remotePath,
            title: executable || sensitiveControl ? "敏感文件与可信基线不一致" : "文件与可信基线不一致",
            detail: hashChanged ? "文件内容哈希已经变化。" : "文件大小或修改时间已经变化。",
            size: file.size,
            modifiedAt: file.modifiedAt,
          });
        } else if (baselineMetadataChanged) {
          metadataChanged += 1;
          addFinding({
            severity: "low",
            category: "metadata-change",
            path: remotePath,
            title: "文件时间或大小变化但内容哈希一致",
            detail: "内容未变化，通常是重新上传或服务器改写时间；保留记录供发布核对。",
            size: file.size,
            modifiedAt: file.modifiedAt,
          });
        }
      }

      if ((executable || sensitiveControl) && remoteHash) {
        if (localFile) {
          const localHash = sha256File(localPath);
          if (localHash !== remoteHash) {
            addFinding({
              severity: sensitiveControl || uploadLike ? "high" : "medium",
              category: "local-mismatch",
              path: remotePath,
              title: "线上代码与本地可信文件不一致",
              detail: "请确认线上是否做过独立修改；若没有，优先按异常篡改处理。",
              size: file.size,
              modifiedAt: file.modifiedAt,
            });
          }
        } else if (executable) {
          remoteOnlyCode += 1;
          addFinding({
            severity: uploadLike ? "high" : "medium",
            category: "remote-only-code",
            path: remotePath,
            title: "线上存在本地没有的可执行脚本",
            detail: "可能是服务器生成文件、旧版本残留或未授权上传，需要人工核对来源。",
            size: file.size,
            modifiedAt: file.modifiedAt,
          });
        }
      }

      options.onProgress?.({
        stage: "content",
        current: index + 1,
        total: tree.files.length,
        contentScanned,
        path: remotePath,
      });
    }

    if (baselineMatches) {
      for (const baselinePath of Object.keys(baseline.files || {})) {
        if (snapshot[baselinePath]) continue;
        missingFiles += 1;
        if (isExecutablePath(baselinePath) || isSensitiveControlFile(baselinePath)) {
          addFinding({
            severity: "medium",
            category: "missing-file",
            path: baselinePath,
            title: "可信基线中的代码文件已消失",
            detail: "可能是正常删除，也可能是异常清理或替换，请与发布记录核对。",
          });
        }
      }
    }

    findings.sort((left, right) => severityWeight(right.severity) - severityWeight(left.severity) || left.path.localeCompare(right.path));
    const severityCounts = findings.reduce((result, item) => {
      result[item.severity] += 1;
      return result;
    }, { high: 0, medium: 0, low: 0 });

    return {
      scannerVersion: 3,
      scanType,
      scanId,
      startedAt,
      finishedAt: new Date().toISOString(),
      fingerprint,
      remoteRoot: normalizeRemoteRoot(config.remoteRoot),
      loginDir: connection.loginDir,
      rootDir: connection.rootDir,
      baseline: { ...baselineInfo(baseline), matchesCurrentSite: baselineMatches },
      summary: {
        files: tree.files.length,
        directories: tree.directoryCount,
        contentScanned,
        newFiles,
        modifiedFiles,
        missingFiles,
        remoteOnlyCode,
        skippedUnchanged,
        metadataChanged,
        timestampAnomalies,
        high: severityCounts.high,
        medium: severityCounts.medium,
        low: severityCounts.low,
        truncated: tree.truncated,
      },
      findings: findings.slice(0, 1500),
      warnings: [...new Set(warnings)].slice(0, 100),
      snapshot,
    };
  } finally {
    await closeConnection();
    fs.rmSync(tempRoot, { recursive: true, force: true });
  }
}

async function downloadEvidence(config, remotePath, options = {}) {
  const normalized = normalizeRemotePath(remotePath);
  if (!normalized) throw new Error("缺少远程文件路径。");
  const connection = await connectFtp(config, options.clientFactory);
  const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
  const evidenceDir = path.join(EVIDENCE_ROOT, timestamp);
  const localPath = safeLocalPath(evidenceDir, normalized);
  fs.mkdirSync(path.dirname(localPath), { recursive: true });
  try {
    await connection.client.downloadTo(localPath, normalized);
    const stat = fs.statSync(localPath);
    const manifest = {
      capturedAt: new Date().toISOString(),
      remotePath: normalized,
      size: stat.size,
      sha256: sha256File(localPath),
    };
    fs.writeFileSync(`${localPath}.evidence.json`, `${JSON.stringify(manifest, null, 2)}\n`, "utf8");
    return { localPath, manifestPath: `${localPath}.evidence.json`, ...manifest };
  } finally {
    connection.client.close();
  }
}

module.exports = {
  BASELINE_PATH,
  HISTORY_PATH,
  EVIDENCE_ROOT,
  appendHistory,
  baselineInfo,
  buildBaseline,
  contentRulesFor,
  createLocalHardeningFiles,
  downloadEvidence,
  hasDoubleExecutableExtension,
  isExecutablePath,
  isUploadLikePath,
  publicScanResult,
  readBaseline,
  readHistory,
  scanRemoteSite,
  siteFingerprint,
  writeBaseline,
};
